# Docker Compose para Desenvolvimento Local (com ngrok)
version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      # Instalar automaticamente o pacote Evolution API
      - N8N_COMMUNITY_PACKAGES=n8n-nodes-evolution-api
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - minha_rede

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - minha_rede

  evolution-api:
    container_name: lab_evolution_api
    image: evoapicloud/evolution-api:latest
    restart: always
    ports:
      - 8080:8080
    volumes:
      - lab_evolution_instances:/lab_evolution/instances
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - minha_rede

  ngrok:
    image: ngrok/ngrok:alpine
    container_name: ngrok
    restart: unless-stopped
    ports:
      - "4040:4040" # interface web do ngrok
    env_file:
      - .env
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    command: start --all --config /etc/ngrok.yml
    depends_on:
      - n8n
      - evolution-api
    networks:
      - minha_rede

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6380:6379"
    networks:
      - minha_rede

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - minha_rede

volumes:
  n8n_data:
  postgres_data:
  lab_evolution_instances:


networks:
  minha_rede:
    driver: bridge
