# render.yaml - Configuração para deploy no Render.com
services:
  # Serviço Web Principal (n8n)
  - type: web
    name: n8n-evoapi-main
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    buildCommand: echo "Build completed"
    startCommand: docker-compose -f docker-compose.prod.yml up
    envVars:
      - key: NODE_ENV
        value: production
      - key: N8N_PASSWORD
        generateValue: true
      - key: AUTHENTICATION_API_KEY
        value: CqSRI6BrIlz45prK3KcLNjBTf+/moPvesMRCYYX5LGQ=
      - key: POSTGRES_PASSWORD
        generateValue: true
      - key: POSTGRES_DB
        value: n8n_evolution_db
      - key: POSTGRES_USER
        value: n8n_user

  # Banco PostgreSQL
  - type: pserv
    name: n8n-evoapi-postgres
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_DB
        value: n8n_evolution_db
      - key: POSTGRES_USER
        value: n8n_user

  # Redis Cache
  - type: redis
    name: n8n-evoapi-redis
    plan: free
    region: oregon